//! Parity against Go — the evidence that the port *behaves* like the original.
//!
//! `tests/testdata/*.txt` are generated by running the equivalent program
//! against `github.com/oklog/ulid/v2` at the base commit. These tests rebuild
//! the same corpora in Rust and compare byte for byte, so a divergence in
//! encoding, parsing, error text, entropy consumption or timestamp arithmetic
//! shows up as a diff rather than as a passing assertion.
//!
//! The goldens are Go's output, not the port's: they were confirmed identical
//! when regenerated on a second platform, so they are a specification, not a
//! snapshot of whatever this crate happened to emit.
//!
//! Set `ULID_DUMP=1` to write the Rust-side corpora to `target/` for
//! inspection when a mismatch needs diagnosing.

use ulid::*;

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

/// Renders like Go's `%v` for an `error` (nil prints as `<nil>`).
fn ev(e: Option<Error>) -> String {
    match e {
        None => "<nil>".to_string(),
        Some(e) => e.to_string(),
    }
}

fn compare(name: &str, produced: &str, golden: &str) {
    if std::env::var("ULID_DUMP").is_ok() {
        let _ = std::fs::write(format!("target/{}.rust.txt", name), produced);
    }
    if produced == golden {
        return;
    }
    let p: Vec<&str> = produced.lines().collect();
    let g: Vec<&str> = golden.lines().collect();
    let mut first = None;
    for i in 0..p.len().max(g.len()) {
        let a = p.get(i).copied().unwrap_or("<missing>");
        let b = g.get(i).copied().unwrap_or("<missing>");
        if a != b {
            first = Some((i + 1, a.to_string(), b.to_string()));
            break;
        }
    }
    match first {
        Some((n, a, b)) => panic!(
            "{}: diverges from Go at line {} of {}\n  rust: {}\n  go  : {}",
            name,
            n,
            g.len(),
            a,
            b
        ),
        None => panic!("{}: same lines but different bytes", name),
    }
}

fn build_ulid_corpus() -> String {
    let mut out = String::new();

    // 1. Derived values over a deterministic ULID corpus.
    let mut r = GoRand::new(20240824);
    let mut prev = ZERO;
    for _ in 0..20000 {
        let mut b = [0u8; 16];
        r.read(&mut b);
        let id = ULID(b);
        let ts = id.timestamp();
        out.push_str(&format!(
            "A|{}|{}|{}|{}|{}|{}|{}\n",
            id,
            id.time(),
            hex(&id.entropy()),
            id.compare(&prev),
            id.is_zero(),
            ts.unix(),
            ts.nanosecond()
        ));
        let txt = id.marshal_text().unwrap();
        let bin = id.marshal_binary().unwrap();
        out.push_str(&format!(
            "B|{}|{}\n",
            std::str::from_utf8(&txt).unwrap(),
            hex(&bin)
        ));

        let up = id.to_string().to_uppercase();
        let lo = id.to_string().to_lowercase();
        out.push_str(&format!("C|{}|{}\n", must_parse(&up), must_parse(&lo)));
        prev = id;
    }

    // 2. Parse / ParseStrict error surface over mutations.
    let base = b"0000XSNJG0MQJHBF4QX1EFD6Y3";
    for i in 0..26usize {
        for c in [0x00u8, 0xFF, b'U', b'i', b'l', b'o', b'8', b'Z'] {
            let mut inp = base.to_vec();
            inp[i] = c;
            let e1 = parse_bytes(&inp).err();
            let e2 = parse_strict_bytes(&inp).err();
            out.push_str(&format!("D|{}|{}|{}|{}\n", i, c, ev(e1), ev(e2)));
        }
    }
    for s in [
        "",
        "x",
        &"Z".repeat(26),
        "80000000000000000000000000",
        "7ZZZZZZZZZZZZZZZZZZZZZZZZZ",
        "00000000000000000000000000",
    ] {
        let e1 = parse(s).err();
        let e2 = parse_strict(s).err();
        out.push_str(&format!("E|{:?}|{}|{}\n", s, ev(e1), ev(e2)));
    }

    // 3. Monotonic sequences (exercises bufio + increment + random()).
    for inc in [0u64, 1, 2, 256, 65536, 4294967296] {
        let rng = GoRand::new(inc as i64 + 777);
        let mut e = monotonic(Box::new(rng), inc);
        for i in 0..500 {
            let (id, err) = new_partial(999, Entropy::Monotonic(&mut e));
            out.push_str(&format!("F|{}|{}|{}|{}\n", inc, i, id, ev(err)));
        }
    }

    // 4. Timestamp/Time conversions incl. boundaries.
    for ms in [
        0u64,
        1,
        999,
        1000,
        1469918176385,
        max_time() - 1,
        max_time(),
    ] {
        let t = time(ms);
        out.push_str(&format!(
            "G|{}|{}|{}|{}\n",
            ms,
            t.unix(),
            t.nanosecond(),
            timestamp(t)
        ));
    }

    // 6. Scan / Value across every accepted dynamic type.
    {
        let seed = must_parse("01ARYZ6S41YYYYYYYYYYYYYYYY");
        let seed_str = seed.to_string();
        let bad_text = "ZZZZZZZZZZZZZZZZZZZZZZZZZZ";
        let inputs: Vec<ScanValue> = vec![
            ScanValue::Str(&seed_str),
            ScanValue::Bytes(&seed.0),
            ScanValue::Bytes(seed_str.as_bytes()),
            ScanValue::Nil,
            ScanValue::Other,
            ScanValue::Bytes(&[1, 2, 3]),
            ScanValue::Bytes(&[]),
            ScanValue::Str(bad_text),
            ScanValue::Str("tooshort"),
        ];
        for (i, inp) in inputs.into_iter().enumerate() {
            let mut o = ULID::default();
            let err = o.scan(inp).err();
            let v = o.value();
            let (vb, verr) = match v {
                Ok(b) => (hex(&b), "<nil>".to_string()),
                Err(e) => (String::new(), e.to_string()),
            };
            out.push_str(&format!("J|{}|{}|{}|{}|{}\n", i, o, ev(err), vb, verr));
        }
    }

    // 7. Partial-read entropy (HalfReader) through New.
    {
        for n in 0..=12usize {
            let buf: Vec<u8> = (0..n).map(|i| (i + 1) as u8).collect();
            let mut src = BytesReader::new(buf);
            let mut hr = HalfReader::new(&mut src);
            let (id, err) = new_partial(7, Entropy::Reader(&mut hr));
            out.push_str(&format!(
                "K|{}|{}|{}|{}\n",
                n,
                id,
                hex(&id.entropy()),
                ev(err)
            ));
        }
    }

    // 8. LockedMonotonicReader sequence (deterministic source).
    {
        let safe = LockedMonotonicReader::new(monotonic(Box::new(GoRand::new(2024)), 0));
        for i in 0..300 {
            let mut h = LockedHandle(&safe);
            let id = must_new(555, Entropy::Monotonic(&mut h));
            out.push_str(&format!("L|{}|{}|{}\n", i, id, hex(&id.entropy())));
        }
    }

    // 9. Monotonic with a non-rng (byte) source, exercising random()'s slow path
    //    across every byte-length bucket.
    {
        for inc in [2u64, 300, 70000, 5000000000] {
            let buf: Vec<u8> = (0..4096).map(|i| ((i * 7 + 3) % 251) as u8).collect();
            let mut m = monotonic(Box::new(BytesReader::new(buf)), inc);
            for i in 0..100 {
                let (id, err) = new_partial(4321, Entropy::Monotonic(&mut m));
                out.push_str(&format!(
                    "M|{}|{}|{}|{}|{}\n",
                    inc,
                    i,
                    id,
                    hex(&id.entropy()),
                    ev(err)
                ));
            }
        }
    }

    // 5. SetTime / SetEntropy error surface.
    let mut id = ULID::default();
    let e1 = id.set_time(max_time() + 1).err();
    let e2 = id.set_entropy(&[1, 2, 3]).err();
    out.push_str(&format!("H|{}|{}\n", ev(e1), ev(e2)));
    out.push_str(&format!(
        "I|{}|{}|{}|{}|{}|{}|{}\n",
        Error::DataSize,
        Error::InvalidCharacters,
        Error::BufferSize,
        Error::BigTime,
        Error::Overflow,
        Error::MonotonicOverflow,
        Error::ScanValue
    ));

    out
}

fn build_sweep_corpus() -> String {
    let base = b"0000XSNJG0MQJHBF4QX1EFD6Y3";
    let mut out = String::new();
    for i in 0..26usize {
        for c in 0..256u32 {
            let mut inp = base.to_vec();
            inp[i] = c as u8;
            let r1 = parse_bytes(&inp);
            let r2 = parse_strict_bytes(&inp);
            // Go returns the (possibly zero) ULID alongside the error.
            let id1 = r1.clone().unwrap_or_default();
            let id2 = r2.clone().unwrap_or_default();
            out.push_str(&format!(
                "S|{}|{}|{}|{}|{}|{}\n",
                i,
                c,
                hex(&id1.0),
                ev(r1.err()),
                hex(&id2.0),
                ev(r2.err())
            ));
        }
    }
    out
}

#[test]
fn parity_ulid_corpus_matches_go() {
    let golden = include_str!("testdata/ulid_golden.txt");
    let produced = build_ulid_corpus();
    compare("ulid_corpus", &produced, golden);
}

#[test]
fn parity_parse_sweep_matches_go() {
    let golden = include_str!("testdata/parse_sweep_golden.txt");
    let produced = build_sweep_corpus();
    compare("parse_sweep", &produced, golden);
}

/// The goldens must be non-trivial; a truncated fixture would let the parity
/// tests pass while proving almost nothing.
#[test]
fn parity_goldens_are_complete() {
    let a = include_str!("testdata/ulid_golden.txt");
    let b = include_str!("testdata/parse_sweep_golden.txt");
    assert_eq!(a.lines().count(), 63_945, "ulid golden truncated");
    assert_eq!(b.lines().count(), 26 * 256, "sweep golden truncated");
    for tag in [
        "A|", "B|", "C|", "D|", "E|", "F|", "G|", "H|", "I|", "J|", "K|", "L|", "M|",
    ] {
        assert!(a.contains(tag), "ulid golden missing section {}", tag);
    }
}
